name: CI/CD Pipeline Deploy Static website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Checkout your repository code

    - name: Deploy to Server
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/deploy_key
        scp -r * ubuntu@100.24.51.230:/var/www/html
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
