name: Deploy Static Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Checkout your repository code

    # Add any steps here that you might need to build your website, if you have a build process
    # For a simple static website with no build process, you can directly proceed to deployment

    - name: Deploy to Server
  if: github.ref == 'refs/heads/main'
  env:
    DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  run: |
    eval "$(ssh-agent -s)"
    ssh-add - <<< "${DEPLOY_KEY}"
    scp -r * ubuntu@100.24.51.230:/var/www/html


