name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to Server
      if: github.ref == 'refs/heads/main'
      run: |
        scp -r * ubuntu@100.24.51.230:/var/www/html
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
