name: CI/CD Pipeline Deploy Static website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Checks out your repository under $GITHUB_WORKSPACE
    
    # Additional steps can go here if you have any build or test steps.
    # Since you're deploying a static site, you might not have these steps.

    - name: Deploy to Server
      if: github.ref == 'refs/heads/main'
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"
        scp -r * ubuntu@100.24.51.230:/var/www/html
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}



