name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Use the latest version of checkout action
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3 # Use the latest version of setup-node action
      with:
        node-version: 'lts/*' # Automatically use the latest LTS version of Node.js

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to Server
      if: github.ref == 'refs/heads/main'
      run: |
        scp -i ${{ secrets.DEPLOY_KEY }} -r * ubuntu@100.24.51.230:/var/www/html
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
